#!/bin/bash

list=(MARIADB_PASS ADMIN_PASS CINDER_DBPASS CINDER_PASS	DASH_DBPASS GLANCE_DBPASS GLANCE_PASS KEYSTONE_DBPASS	NEUTRON_DBPASS NEUTRON_PASS NOVA_DBPASS	NOVA_PASS RABBIT_PASS PLACEMENT_PASS METADATA_SECRET)

for username in "${list[@]}"
do
	password=`openssl rand -hex 10`
	echo $username: $password
done
echo DEMO_PASS: demo1234
